// An example of passing functions as parameters.
// Generated by ChatGpt

// Define an array of numbers
const numbers = [1, 2, 3, 4, 5];

// Define functions for different operations
function square(x) {
  return x * x;
}

function double(x) {
  return x * 2;
}

// Higher-order function to perform an operation on each number
function processNumbers(numbersArray, operation) {
  const result = [];
  for (const number of numbersArray) {
    result.push(operation(number));
  }
  return result;
}

// Use the processNumbers function with different operations
const squaredNumbers = processNumbers(numbers, square);
console.log(squaredNumbers); // Output: [1, 4, 9, 16, 25]

const doubledNumbers = processNumbers(numbers, double);
console.log(doubledNumbers); // Output: [2, 4, 6, 8, 10]
